let statename=["AndhraPradesh",
    "ArunachaPradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "HimachalPradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Maharashtra",
    "Madhya-Pradesh",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamilnadu",
    "Tripura",
    "Telangana",
    "Uttarpradesh",
    "Uttarakhand",
    "WestBengal",
    "Andaman & Nicobar",
    "Chandigarh",
    "Dadra & Nagarhaveli & Daman & Diu" ,
    "Delhi",
    "Jammu & Kashmir ",
    "Ladakh" ,
    "Lakshadweep ",
    "Puducherry"];
let intro={
        "name":"souvik","age":31
    };